obj-$(CONFIG_AM_CXD2837) += cxd2837_fe.o

cxd2837_fe-objs = cxd2861_cxd2837_api.o sony_ascot2e.o sony_tuner_ascot2e.o sony_ascot3.o sony_tuner_ascot3.o cxd2837frontend.o sony_common.o \
						sony_demod.o  sony_demod_dvbc_monitor.o sony_demod_dvbc.o sony_demod_dvbt_monitor.o sony_demod_dvbt2_monitor.o \
						sony_demod_dvbt2.o sony_demod_dvbt.o sony_integ.o sony_integ_dvbt_t2.o sony_integ_dvbc.o\
						sony_i2c.o sony_math.o sony_stopwatch_port.o sony_trace.o \
						mxl603/MxL603_Main.o	mxl603/MxL603_OEM_Drv.o	mxl603/MxL603_TunerApi.o	mxl603/MxL603_TunerCfg.o mxl603/MxL603_TunerSpurTable.o

EXTRA_CFLAGS += -Idrivers/media/dvb-core

